database:
  connectionString: postgres://devuser:devpassword@localhost:15432/devdb?sslmode=disable

kafka:
  brokers: localhost:9092
  topics:
    order: oms.oms-core.orders.v1
    assemblyApplication: oms.oms-core.assembly-application.v1

server:
  address: 8888